### ISSUE TITLE
[data] Cornell Move Dialog Corpus

### ISSUE THREAD

**Issue by at15** [at15/snowbot#6]
- https://www.cs.cornell.edu/~cristian/Cornell_Movie-Dialogs_Corpus.html
- https://www.kaggle.com/Cornell-University/movie-dialog-corpus  provides more detail on meta data

Other people's preprocess

- [x] https://github.com/b0noI/dialog_converter used by https://blog.kovalevskyi.com/rnn-based-chatbot-for-6-hours-b847d2d92c43 (it seems forgot to use the conversation file ...)
- https://github.com/suriyadeepan/datasets/blob/master/seq2seq/cornell_movie_corpus/scripts/prepare_data.py

TODO

- [x] the separator is '+++$+++', and is treated as regexp by pandas ...
   - need to parse the data manually
- [x] turn conversation into one turn QA
  - [ ] what about multi turn? (sensitive to context)

**Comment by at15** [comment]
migrated from #9 

TODO

- [x] the way we construct Q & A, we just need to shift Q one line to get A ....
  - it is **not** the case, because we have many conversations, for each conversation it shifts one line, for their combination, it's not
- [x] found float inside string when convert into encoder, decoder file
  - empty string is treated as NAN ... we can use df.fillna('') https://github.com/pandas-dev/pandas/issues/10205

````
write to train_enc.txt
199455
Traceback (most recent call last):
  File "cornell.py", line 159, in <module>
    cli()
  File "/home/at15/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/at15/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/at15/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/at15/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/at15/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "cornell.py", line 115, in convert
    f.write('\n'.join(data))
TypeError: sequence item 2289: expected str instance, float found
````

- [ ] find out how many I don't know it has ...

**Comment by at15** [comment]
I think I am done with this dataset .... I don't know, what do you want to me do? ...
