### ISSUE TITLE
[data] Cornell Movie Dialog Corpus

### ISSUE THREAD

**Issue by at15** [at15/snowbot#9]
TODO

- [x] the way we construct Q & A, we just need to shift Q one line to get A ....
  - it is **not** the case, because we have many conversations, for each conversation it shifts one line, for their combination, it's not
- [x] found float inside string when convert into encoder, decoder file
  - empty string is treated as NAN ... we can use df.fillna('') https://github.com/pandas-dev/pandas/issues/10205

````
write to train_enc.txt
199455
Traceback (most recent call last):
  File "cornell.py", line 159, in <module>
    cli()
  File "/home/at15/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/at15/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/at15/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/at15/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/at15/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "cornell.py", line 115, in convert
    f.write('\n'.join(data))
TypeError: sequence item 2289: expected str instance, float found
````

- [ ] find out how many I don't know it has ...

**Comment by at15** [comment]
merged with #6
